# Generated by Django 4.2.5 on 2023-09-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0002_course_altsubject_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='altsubject',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=64),
        ),
    ]
