# Generated by Django 4.2.5 on 2023-09-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0003_alter_course_altsubject_alter_course_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='altsubject',
            new_name='subjectid',
        ),
    ]
