# Generated by Django 4.2.5 on 2023-09-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0004_rename_altsubject_course_subjectid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subjectid',
            new_name='subject_id',
        ),
    ]
