# Generated by Django 4.2.5 on 2023-09-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0005_rename_subjectid_course_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Semester',
            field=models.CharField(default='t', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(default='t', max_length=4),
        ),
    ]
