# Generated by Django 4.2.5 on 2023-09-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0006_course_semester_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Semester',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
