# Generated by Django 4.2.5 on 2023-09-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0007_alter_course_semester_alter_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
