# Generated by Django 4.2.5 on 2023-09-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0008_course_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Semester',
            new_name='seatemester',
        ),
    ]
