# Generated by Django 4.2.5 on 2023-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('subject_id', models.CharField(max_length=5)),
                ('semester', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('seat', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='student', to='users.course'),
        ),
    ]
