# Generated by Django 4.2.5 on 2023-09-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_course_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
