# Generated by Django 4.2.5 on 2023-09-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_student_id_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='-', max_length=64),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='-', max_length=10),
        ),
    ]
